name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.12"]
        
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Fix the imports with isort
      run: |
        isort --trailing-comma nucs tests
    - name: Format the code with black
      run: |
        black nucs tests
    - name: Fix the style with flake8
      run: |
        flake8 nucs tests
    - name: Static typing with mypy
      run: |
        mypy --disallow-untyped-defs --ignore-missing-imports nucs tests
    - name: Test with pytest
      run: |
        PYTHONPATH=. pytest tests
